DocsPortingTool/Configuration.cs
DocsPortingTool/Docs/DocsCommentsContainer.cs
DocsPortingTool/Log.cs
DocsPortingTool/Properties/launchSettings.json
DocsPortingTool/TripleSlash/TripleSlashCommentsContainer.cs
DocsPortingTool/TripleSlash/TripleSlashException.cs
DocsPortingTool/TripleSlash/TripleSlashMember.cs
Tests/TestData.cs
Tests/TestData/AssemblyAndNamespaceDifferent/DocsExpected.xml
Tests/TestData/AssemblyAndNamespaceDifferent/DocsOriginal.xml
Tests/TestData/AssemblyAndNamespaceDifferent/TSOriginal.xml
Tests/TestData/AssemblyAndNamespaceSame/DocsExpected.xml
Tests/TestData/AssemblyAndNamespaceSame/DocsOriginal.xml
Tests/TestData/AssemblyAndNamespaceSame/TSOriginal.xml
Tests/Tests.cs

Most namespaces have the same name as their assembly. There are a few cases though, where this is not the case. For those cases, the tool was not able to detect new comments easily.
This change fixes the problem by adding a new couple of arguments: `-IncludedNamespaces` and `-ExcludedNamespaces`, which can be optionally specified by the user if the assembly is different than the namespace.
If not explicitly specified, then the tool will assume the namespace is the same as the assembly name.

Handle namespace and assembly separately

---

DocsPortingTool/Analyzer.cs
DocsPortingTool/Docs/DocsAssemblyInfo.cs
DocsPortingTool/Docs/DocsCommentsContainer.cs
DocsPortingTool/TripleSlash/TripleSlashCommentsContainer.cs
Tests/TestData/Remarks_WithEII_NoInterfaceRemarks/DocsExpected.xml
Tests/TestData/Remarks_WithEII_NoInterfaceRemarks/DocsOriginal.xml
Tests/TestData/Remarks_WithEII_NoInterfaceRemarks/TSOriginal.xml

Fix bug preventing to find all cases of types that live in namespaces different than their assemblies.
Simplify code so that verification tasks for included/excluded items are not done more than once.
Cleanup.
Make sure one of the sets of EII test files has assembly = namespace. The other one will remain with assembly != namespace.

Assembly namespace bug fix

---

DocsPortingTool/Analyzer.cs
DocsPortingTool/Docs/DocsAPI.cs
DocsPortingTool/Docs/DocsMember.cs
DocsPortingTool/Docs/DocsType.cs
DocsPortingTool/XmlHelper.cs
Tests/TestData/DontAddMissingRemarks/DocsExpected.xml
Tests/TestData/DontAddMissingRemarks/DocsOriginal.xml
Tests/TestData/DontAddMissingRemarks/TSOriginal.xml
Tests/TestData/Remarks_NoEII_NoInterfaceRemarks/DocsExpected.xml
Tests/TestData/Remarks_WithEII_NoInterfaceRemarks/DocsExpected.xml
Tests/TestData/Remarks_WithEII_WithInterfaceRemarks/DocsExpected.xml
Tests/Tests.cs

There are certain API elements (types or members) that do not have a remarks item by default in Docs xmls. Currently, the tool automatically adds it if it's missing, but it shouldn't.
The logic has been modified so that the remarks item only gets added if there is a remarks section in the triple slash xml for that same API element.
Added unit tests to verify we don't add a remarks item every time, but only if a remarks item is incoming from triple slash.
I also added a minor fix in the spacing handling for the markdown CDATA in remarks, and adjusted the existing unit tests accordingly.

Don't add missing remarks

---

Libraries/Docs/DocsCommentsContainer.cs
Libraries/Log.cs
Libraries/RoslynTripleSlash/TripleSlashSyntaxRewriter.cs
Libraries/ToTripleSlashPorter.cs
Tests/PortToTripleSlash/TestData/Basic/MyDelegate.xml
Tests/PortToTripleSlash/TestData/Basic/MyEnum.xml
Tests/PortToTripleSlash/TestData/Basic/MyType.xml
Tests/PortToTripleSlash/TestData/Basic/SourceExpected.cs
Tests/PortToTripleSlash/TestData/Basic/SourceOriginal.cs

If a symbol is not found in the main project, we look for it in the referenced projects. If one of the projects happens to be System.Private.CoreLib, and we don't find the symbol in the Libraries version, then we have to try to find it in the Mono version.
If a symbol has multiple implementations for different platforms, ensure to port comments to those files too.
cc @safern

Add ability to find symbol in mono corelib and in other platform locations

---

Libraries/Extensions.cs
Libraries/RoslynTripleSlash/TripleSlashSyntaxRewriter.cs
Tests/PortToTripleSlash/TestData/Basic/MyDelegate.xml
Tests/PortToTripleSlash/TestData/Basic/MyType.xml
Tests/PortToTripleSlash/TestData/Basic/SourceExpected.cs

Increase the cases that allow converting markdown to xml, so we have fewer remarks backported as markdown.

Convert links and examples in remarks as xml

---

install-as-tool.ps1

@eiriktsarpalis thanks for catching the issue. Program should not be used as a publishing project name or it would collide with others.
Can you help me verify that this fix works for you?

Fix install-as-tool script

---

Libraries/RoslynTripleSlash/TripleSlashSyntaxRewriter.cs
Tests/PortToTripleSlash/TestData/Basic/MyEnum.xml
Tests/PortToTripleSlash/TestData/Basic/MyType.xml
Tests/PortToTripleSlash/TestData/Basic/SourceExpected.cs
Tests/PortToTripleSlash/TestData/Basic/SourceOriginal.cs

If a public API has double slash comments, there's no need to replace them with triple slash because they may contain information that is critical to code maintainers. So I'm putting them at the bottom after adding the triple slash comments.
Detecting some more markdown elements and converting them to their xml equivalent.
Detecting `[!TIP]` and keeping it as markdown.
Added these cases to unit test.

Preserve double slash comments in public APIs, and some markdown conversions

---

Libraries/ToTripleSlashPorter.cs

The tool receives a list of namespaces from the command line arguments. The user can filter the types they want to backport by specifying their namespaces.
The tool looks at the project name and determines if it was included or excluded by the user, but I forgot to skip System.Private.CoreLib from this check because it's a special project that should always be included.
I fixed it by detecting when this project is being analyzed and skip the namespace check when S.P.CoreLib is the current project.
@tannergooding

Fix bug preventing loading types from System.Private.CoreLib

---

Libraries/ToTripleSlashPorter.cs

This typo was preventing diagnostic errors from showing up.
@tannergooding @eiriktsarpalis after I merge this, can you please update the tool, rerun it and then send me the diagnostic errors you're getting?
This is the error I am getting in my machine:
```
Diagnostic messages found in workspace.OpenProjectAsync - MyAssembly.csproj:
Failure - Msbuild failed when processing the file 'ProjectMyAssembly.csproj' with message:
The SDK resolver type "WorkloadSdkResolver" failed to load.
Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
The system cannot find the file specified.
```
Knowing which error you get will help @safern and I investigate the root cause.

Count condition was wrong

---

Program/DocsPortingTool.csproj

The reason why this was failing is because the old MSBuild locator was resolving the newest SDK regardless of the runtime that the tool was running on. This: https://github.com/microsoft/MSBuildLocator/issues/92 fixed that issue and only returns SDKs that are same or earlier than the runtime the tool is running on. 
cc: @carlossanlop

Update MSBuild locator to not resolve SDKs newer than the runtime

---

.github/workflows/dotnet.yml
DocsPortingTool.sln
Libraries/Libraries.csproj
Program/DocsPortingTool.csproj
Tests/Tests.csproj

Related to https://github.com/carlossanlop/DocsPortingTool/pull/40
cc @safern @ericstj

Upgrade to net6.0 to prevent dependency issues after upgrading MSBuild.Locator

---

BackportInstructions.md
Libraries/Libraries.csproj
Program/DocsPortingTool.csproj
README.md
Tests/Tests.csproj

Upgrade nuget packages to fix unit test failure.
Also update instructions with new information.

Update nuget packages and instructions

---

Libraries/ToTripleSlashPorter.cs
README.md

Fixed bug preventing the tool from looking for Mono source code.
Improved speed by caching the workspaces, projects and compilations that are opened each time. No need to reopen them from scratch when exploring references.
Minor fix in readme.

Bug fixes: Mono symbols can't be found. Tool is slow.

---

BackportInstructions.md
Libraries/RoslynTripleSlash/TripleSlashSyntaxRewriter.cs
Tests/PortToTripleSlash/TestData/Basic/MyType.xml
Tests/PortToTripleSlash/TestData/Basic/SourceExpected.cs

Fixes #41 
Fixes #39 
Improve and simplify regex detection to:
- Fix bug causing xrefs to not be properly detected.
- Fix bug causing cref generic typeparams to not be replaced with `{T}` (limited fix).
Update documentation indicating new cases that can be handled.

Fix bugs in xref detection and cref typeparams

---

Libraries/RoslynTripleSlash/TripleSlashSyntaxRewriter.cs
Tests/PortToTripleSlash/TestData/Basic/SourceExpected.cs

Fixes #43
Add exceptions before remarks.
Add typeparams before params.
cc @eiriktsarpalis

Change order of triple slash items

---

Libraries/Docs/DocsType.cs
Libraries/ToTripleSlashPorter.cs
Tests/PortToTripleSlash/PortToTripleSlashTestData.cs
Tests/PortToTripleSlash/PortToTripleSlashTests.cs
Tests/PortToTripleSlash/TestData/Generics/MyAssembly.csproj
Tests/PortToTripleSlash/TestData/Generics/MyGenericType`1+Enumerator.xml
Tests/PortToTripleSlash/TestData/Generics/MyGenericType`1.xml
Tests/PortToTripleSlash/TestData/Generics/SourceExpected.cs
Tests/PortToTripleSlash/TestData/Generics/SourceOriginal.cs
Tests/Tests.csproj

Generic and nested type names were not getting formatted correctly. This was preventing docs for those types from getting ported into triple slash comments.
This was discovered while attempting to port `System.Buffers` and `System.Memory` for dotnet/runtime#48967 and dotnet/runtime#48964. The first symptom was that `ArrayPool<T>` docs were not getting ported. The second symptom was that `ReadOnlySequence<T>.Enumerator` docs were not getting ported.
Based on this discovery, I suspect any libraries already ported that contain public generic or nested types would need to have the tool rerun.

Use the correct type name for generic and nested types

---

Libraries/Docs/DocsCommentsContainer.cs
Libraries/IntelliSenseXml/IntelliSenseXmlCommentsContainer.cs
Libraries/RoslynTripleSlash/TripleSlashSyntaxRewriter.cs
Libraries/ToDocsPorter.cs
Libraries/ToTripleSlashPorter.cs

When doing a large run, these lists become large and I noticed the O(n) scans became a hot path.
NOTE: this detected that we were previously adding entries to the lists that had the same doc ID as existing entries. The code was just finding the first. To keep that behavior i changed to TryAdd. It's not clear whether this is a bug.

Change lists to dictionaries

---

Libraries/Docs/DocsCommentsContainer.cs
Libraries/IntelliSenseXml/IntelliSenseXmlCommentsContainer.cs

Remove expensive file existence checks - it will throw if they don't exist.
Read docs xml files in the correct codepage (it chokes eg on Char.xml otherwise). We already save in 1252.
Include file path when failing to read/write the XML.

XML read/write

---

Libraries/Log.cs
Libraries/ToTripleSlashPorter.cs
Program/DocsPortingTool.cs

Move console writes to a separate thread.
On that thread, batch the calls to console. 
Don't continue batching if the color changes.
Don't continue batching if it's been over a second. [Note, this isn't perfect; if another message doesn't come in for a while, it will wait. But it will never fail to write.]
Add logging to a file, since a large run will exhaust the console buffer.
With these changes, a small run was sped up from about 10-11 sec to 7 sec. When running over the whole tree, it can save minutes.
@stephentoub this is my first time using DataFlow blocks. Does it seem reasonable?

Speed up execution by offloading logging

---

Libraries/XmlHelper.cs

Noticed it was doing a match twice. I believe this showed up in the profile but I can't claim it was much.
Also added a note about a true bottleneck. In a large run, `string.Join("", element.Nodes())` is taking up to 50% of the time. I experimented with the commented out code, which is significantly faster but still a bottleneck. however, the spacing is slightly different (better, I think) and I don't know enough about whether it matters.

Minor perf change

---

Libraries/Docs/DocsAPI.cs
Libraries/Docs/DocsMember.cs
Libraries/Docs/DocsType.cs
Libraries/Docs/IDocsAPI.cs
Libraries/ToDocsPorter.cs

Delegates can have return values, but return values were only being detected in members, not in types (and delegates are types).
Example of an API that was not getting its return value ported:
https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.InteropServices.ObjectiveC/ObjectiveCMarshal+UnhandledExceptionPropagationHandler.xml#L21
cc @jeffhandley @aaronrobinsonmsft

Detect <returns> in delegate types.

---

Libraries/Configuration.cs
Libraries/Docs/DocsCommentsContainer.cs
Libraries/Log.cs
Libraries/ToDocsPorter.cs
Program/DocsPortingTool.cs
Program/DocsPortingTool.csproj
Tests/PortToDocs/PortToDocsTests.cs
Tests/PortToDocs/TestData/EnumRemarks/intellisense/MyAssembly/MyAssembly.xml
Tests/PortToDocs/TestData/EnumRemarks/xml/MyAssembly/MyType.xml
Tests/PortToDocs/TestData/EnumRemarks/xml_expected/MyAssembly/MyType.xml

- The parameter prompt won't show up by default. The user will be asked for it only if they specify the cmdline argument `-DisablePrompts false`.
- Reverted the Channels code change. It was slowing the tool by a lot, and preventing some messages from getting printed.
- Enum remarks are not ported.
- Made logging less verbose. Hid it behind the `-PrintSummaryDetails true` cmdline argument.
- Fix the encoding issue causing the original encoding from getting preserved.

Various fixes

---

Tests/PortToDocs/PortToDocsTests.cs
Tests/PortToTripleSlash/PortToTripleSlashTestData.cs
Tests/PortToTripleSlash/PortToTripleSlashTests.cs
Tests/TestDirectory.cs
global.json

To get rid of the CI test failure when there are missing usings.

Bump .NET 6.0 version in global.json

---

Libraries/Docs/DocsAPI.cs
Libraries/Docs/DocsException.cs
Libraries/Docs/DocsMember.cs
Libraries/Docs/DocsType.cs
Libraries/Extensions.cs
Libraries/IntelliSenseXml/IntelliSenseXmlMember.cs
Libraries/ToDocsPorter.cs
Tests/PortToDocs/TestData/Basic/intellisense/MyAssembly/MyAssembly.xml
Tests/PortToDocs/TestData/Basic/xml/MyAssembly/MyType.xml
Tests/PortToDocs/TestData/Basic/xml_expected/MyAssembly/MyType.xml

This is due to special formatting characters being part of some docIds: `{` and `}`.
Ensure all docIds get escaped everywhere (whether they come from intellisense xmls or from docs xmls) so they can be compared correctly, and so they don't cause exceptions when attempting to print them.

Fix bug preventing some DocId from being properly printed/matched

---

Libraries/IntelliSenseXml/IntelliSenseXmlMember.cs
Program/DocsPortingTool.csproj

Winforms intellisense xml files have an assembly xml item wrapped by endlines:
```xml
<?xml version="1.0"?>
<doc>
<assembly>
<name>
Microsoft.VisualBasic.Forms
</name>
</assembly>
```
Which caused the `IntelliSenseXmlMember.Assembly` string to get extracted as `\nMicrosoft.VisualBasic.Forms\n`, preventing the files to be matched correctly.
cc @dreddy-work

Trim assembly name extracted from IntelliSense xml file.

---

install-as-tool.ps1

@eiriktsarpalis you helped add this script. Can you please review this change?
Ideally, we would bump the DocsPortingTool version every time we merge a PR, but we sometimes forget (I'm guilty of this).
The `dotnet tool update` command only updates a package if the version is greater than the one installed. Unfortunately, it does not have a `-force` option to overwrite the existing package if it's the same version.
So instead, what I want to do is look for any instances of it, uninstall them, then install the tool again. And this will only be done if packing succeeds (The `dotnet` process will return `0` on success).

Update install as tool

---

src/PortToDocs/src/app/PortToDocs.cs
src/PortToDocs/src/libraries/Docs/DocsCommentsContainer.cs
src/PortToDocs/src/libraries/IntelliSenseXml/IntelliSenseXmlCommentsContainer.cs
src/PortToDocs/src/libraries/ToDocsPorter.cs
src/PortToDocs/tests/PortToDocs/PortToDocsTests.cs

Unit testing is too hard in the PortToDocs project because the only method we currently use requires creating real files and modifying them as they would in a real use case scenario.
We can keep the tests we already have but we should also have the ability to create tests that don't depend on the filesystem and which allow passing the document to read and the document to write.
This is the first iteration. In the next iteration (maybe next commit, or maybe next PR) I will add unit tests using this simplified process.

PortToDocs: Add methods that either collect files automatically, or allow passing documents manually

---

src/PortToDocs/src/app/PortToDocs.cs
src/PortToDocs/src/libraries/Configuration.cs
src/PortToDocs/src/libraries/Docs/DocsCommentsContainer.cs
src/PortToDocs/src/libraries/ToDocsPorter.cs
src/PortToDocs/tests/PortToDocs/PortToDocs.FileSystem.Tests.cs
src/PortToDocs/tests/PortToDocs/PortToDocs.Strings.Tests.cs

Fixes https://github.com/dotnet/api-docs-sync/issues/106
When a typeparam name is changed in triple slash, the identifier does not get updated in api docs: the old name always remains, except in the DocId.
The tool was adding extra typeparam items in the docs xmls, which is not correct. Instead, the tool should ask the user which triple slash typeparams need to be mapped to the docs typeparams. But the only condition is that the user should pass `DisablePrompts=false` to the console.
This sounds like it's also a bug on the docs side: Ideally, we should have both the old and the new names indicated in the typeparams section, but that's something we should discuss with the docs dev team.
I also added the first unit test that does not rely on the filesystem. For that, I needed to tweak the …

Detect renamed typeparam, prompt user to select the correct renamed typeparam

---

src/PortToDocs/src/app/PortToDocs.csproj
src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs/PortToDocs.Strings.Tests.cs

Fixes https://github.com/dotnet/api-docs-sync/issues/105
If a `<seealso cref="DocId"/>` is found in markdown, make sure it gets ported as `<xref:DocId>`.
Also found two closely related bugs:
- When detecting `<typeparamref name="name"/>`, need to make sure it gets converted to `name` in markdown.
- When finding a `see|seealso cref` pointing to a primitive type, need to handle them in a special way: Preserve the primitive type name in markdown, but in xml convert it to the full DocId.
Added individual string tests for each one of the different conversions.

Fix bug preventing markdown proper conversion of various xml elements (see, seealso, paramref, typeparamref)

---

src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs/PortToDocs.Strings.Tests.cs

Fixes https://github.com/dotnet/api-docs-sync/issues/117

Detect backticks in remarks xrefs and convert them to %60

---

src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs/PortToDocs.Strings.Tests.cs

Fixes https://github.com/dotnet/api-docs-sync/issues/117
Found a bug when I ran the tool again. Need to only replace backticks when inside an xref, not all of them.
Also added regex to detect `#ctor` and convert it to `%23ctor`.

Improve regex to replace backticks in xrefs, add regex to replace #ctor in xrefs

---

src/PortToDocs/src/libraries/Log.cs
src/PortToTripleSlash/src/app/PortToTripleSlash.cs
src/PortToTripleSlash/src/libraries/Configuration.cs
src/PortToTripleSlash/src/libraries/Docs/DocsCommentsContainer.cs
src/PortToTripleSlash/src/libraries/Log.cs
src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlashTests.cs

After splitting the two tools, I realized I left some help strings and config options that do not belong anymore.
Also added a missing copyright header.

Remove unused Log Help options

---

src/PortToDocs/src/app/PortToDocs.csproj
src/PortToDocs/src/libraries/Configuration.cs
src/PortToDocs/src/libraries/Docs/DocsAPI.cs
src/PortToDocs/src/libraries/Docs/DocsMember.cs
src/PortToDocs/src/libraries/Docs/DocsType.cs
src/PortToDocs/src/libraries/Log.cs
src/PortToDocs/src/libraries/ToDocsPorter.cs
src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs/PortToDocs.FileSystem.Tests.cs
src/PortToDocs/tests/PortToDocs/PortToDocs.Strings.Tests.cs

@gewarren I finally got time to address this.

Port to docs the remarks as xml by default instead of markdown

---

.github/workflows/dotnet.yml

Need to re-enable in this PR when the issue gets fixed. https://github.com/dotnet/api-docs-sync/pull/124

Disable Test PortToTripleSlash workflow job

---

src/PortToDocs/src/libraries/Docs/DocsAPI.cs
src/PortToDocs/src/libraries/Docs/DocsException.cs
src/PortToDocs/src/libraries/IntelliSenseXml/IntelliSenseXmlMember.cs
src/PortToDocs/src/libraries/ToDocsPorter.cs
src/PortToDocs/tests/PortToDocs.Strings.Tests.cs

- Avoid escaping crefs except when printing to log.
- Make sure params and typeparams are also ported when inheriting from base type or interface.
- Add tests.
Future TODO: Implement functionality for `-PreserveInheritDocTag false` and add tests: https://github.com/dotnet/api-docs-sync/issues/129

Fix inheritdoc bugs for full or partial inheritance

---

src/PortToTripleSlash/src/app/PortToTripleSlash.cs
src/PortToTripleSlash/src/app/PortToTripleSlash.csproj
src/PortToTripleSlash/src/libraries/Configuration.cs
src/PortToTripleSlash/src/libraries/Docs/DocsType.cs
src/PortToTripleSlash/src/libraries/Log.cs
src/PortToTripleSlash/src/libraries/MSBuildLoader.cs
src/PortToTripleSlash/src/libraries/ToTripleSlashPorter.cs
src/PortToTripleSlash/src/libraries/VSLoader.cs
src/PortToTripleSlash/src/libraries/libraries.csproj
src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlashTestData.cs
src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlashTests.cs
src/PortToTripleSlash/tests/PortToTripleSlash/TestData/Basic/MyAssembly.csproj
src/PortToTripleSlash/tests/PortToTripleSlash/TestData/Generics/MyAssembly.csproj
src/PortToTripleSlash/tests/tests.csproj

Some fixes to get the tool working back again, @RussKie @jeffhandley.
It works if you execute it manually. It doesn't work when executed from the unit tests due to https://github.com/dotnet/roslyn/issues/61454.
Changes in this PR:
- Updated the projects to net7.0, otherwise we are unable to load the target projects in dotnet/runtime.
- Separated the code that loads the VS instance and the code that loads MSBuild, because as described in the documentation, you must not load Microsoft.Build APIs in the same context where you're loading MSBuildLocator APIs. This includes BinLogger APIs. https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application
- Made the project loading code much faster by loading the workspaces, projects and compilations only once.
- Simplified …

Fix Triple Slash Porter MSBuild loading

---

src/PortToTripleSlash/src/libraries/AllTypesVisitor.cs
src/PortToTripleSlash/src/libraries/Docs/DocsAPI.cs
src/PortToTripleSlash/src/libraries/Docs/DocsMember.cs
src/PortToTripleSlash/src/libraries/Docs/DocsType.cs
src/PortToTripleSlash/src/libraries/Docs/IDocsAPI.cs
src/PortToTripleSlash/src/libraries/MSBuildLoader.cs
src/PortToTripleSlash/src/libraries/ResolvedLocation.cs
src/PortToTripleSlash/src/libraries/ResolvedProject.cs
src/PortToTripleSlash/src/libraries/ResolvedWorkspace.cs
src/PortToTripleSlash/src/libraries/ToTripleSlashPorter.cs
src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlashTests.cs
src/PortToTripleSlash/tests/PortToTripleSlash/TestData/Basic/MyAssembly.csproj
src/PortToTripleSlash/tests/PortToTripleSlash/TestData/Basic/MyDelegate.xml
src/PortToTripleSlash/tests/PortToTripleSlash/TestData/Basic/SourceExpected.cs
src/PortToTripleSlash/tests/PortToTripleSlash/TestData/Basic/SourceOriginal.cs
src/PortToTripleSlash/tests/PortToTripleSlash/TestData/Generics/MyAssembly.csproj

After fixing the MSBuild problem, the unit tests uncovered a problem when attempting to detect nested types, specifically, delegates. Turns out the way symbols were being visited before was not a proper way of ensuring nested types would also be visited. Instead, I added a CSharpVisitor instance and now all the symbols get pre-collected, and then paired up with the docs types afterwards.
The tests now pass.

Fix detection of nested types

---

src/PortToTripleSlash/src/libraries/ToTripleSlashPorter.cs
src/PortToTripleSlash/tests/PortToTripleSlash.Strings.Tests.cs
src/PortToTripleSlash/tests/PortToTripleSlash/StringTestData.cs

Found a bug preventing finding delegate types when verifying that they were ported.

Fix delegate finding logic in tests

---

src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlash.Strings.Tests.cs

Some strings in the nested type tests were incorrect, causing failures.

Fix nested types tests

---

src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlash.Strings.Tests.cs

The `DocsMember` elements **must** have a `MemberType`  xml value to indicate if it's a method or a property. I missed adding those in the test xml strings.

Fix property tests that are failing

---

src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlash.Strings.Tests.cs

Operator tests were not working because the DocID was incorrectly cased.
Also added other missing property MemberType items.

Fix operators docIds, add more MemberType for properties.

---

src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlash.Strings.Tests.cs

Turns out the docs xml files indicate generic parameters with a double back tick, not a single one.
Also added more tests that verified different types of arguments and return values, and renamed them all properly.

Fix generic method tests

---

src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlash.Strings.Tests.cs

Turns out the DocID of a parameterless constructor is `#ctor` not `#ctor()`.
Added an extra set of tests for constructors with parameters.

Fix constructor tests

---

src/PortToTripleSlash/tests/PortToTripleSlash/PortToTripleSlash.Strings.Tests.cs
src/PortToTripleSlash/tests/tests.csproj

Added XUnitExtensions to be able to top tests with known problems using the `ActiveIssue` attribute. Updated required dependency XUnit too.
Add test to verify that double slash comments are preserved.
Add test to verify that triple slash items that have nothing to backport, remain untouched. This test is currently failing and I opened https://github.com/dotnet/api-docs-sync/issues/149 to track it.

Additional tests around comment special cases

---

.github/workflows/dotnet.yml
build.proj
src/PortToDocs/src/app/PortToDocs.csproj
src/PortToDocs/src/libraries/libraries.csproj
src/PortToDocs/tests/tests.csproj
src/PortToTripleSlash/src/app/PortToTripleSlash.csproj
src/PortToTripleSlash/src/libraries/libraries.csproj
src/PortToTripleSlash/tests/tests.csproj

Fixes https://github.com/dotnet/api-docs-sync/issues/155
- Bump the `TargetFramework` of all the api-docs-sync projects to `net8.0`.
- Update the dependencies versions to the latest available in the feeds.
- Add a `build.proj` file in the root folder to make it possible to run `dotnet build/restore/clean/test` from the root folder.
- Bump the versions of the projects to the next number.
Tests:
- Confirmed that the project can be build and tests can be successfully executed from Visual Studio.
- Confirmed that all the `dotnet build/restore/clean/test` commands run successfully from the root.
- Confirmed that `install-as-root.ps1` works well (detects `build.proj` and uses it).
- Confirmed with System.IO.Compression.Brotli that the tool is capable of porting docs.

Fix real scenario execution failure

---

src/PortToDocs/src/libraries/Configuration.cs
src/PortToDocs/src/libraries/Docs/DocsCommentsContainer.cs
src/PortToDocs/src/libraries/Docs/DocsException.cs
src/PortToDocs/src/libraries/ToDocsPorter.cs
src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs.Strings.Tests.cs
src/PortToDocs/tests/StringTestData.cs

The `<para>` items were being removed on purpose. Removed that code.
Cleaned newline handling, force it to always be LF instead of CRLF.
The way xml handles newlines also changed recently and broke all tests (loading an XDocument transforms them to Environment.NewLine). Fixed that too.

Ensure `<para>` items are ported

---

src/PortToDocs/src/libraries/Configuration.cs
src/PortToDocs/src/libraries/Docs/DocsAPI.cs
src/PortToDocs/src/libraries/Docs/DocsMember.cs
src/PortToDocs/src/libraries/Docs/DocsSeeAlso.cs
src/PortToDocs/src/libraries/IntelliSenseXml/IntelliSenseXmlMember.cs
src/PortToDocs/src/libraries/IntelliSenseXml/IntelliSenseXmlSeeAlso.cs
src/PortToDocs/src/libraries/ToDocsPorter.cs
src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs.Strings.Tests.cs

@gewarren 
I noticed the seealso cref elements inside other xml elements like summary, returns, etc. were not being converted to see crefs, so I fixed that.
I made sure to preserve seealso cref elements that are outside those xml elements, or in other words, direct children of the Docs element.
Added test to verify this. All tests pass locally.

Fix seealso cref handling

---

src/PortToDocs/src/app/PortToDocs.csproj
src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs.Strings.Tests.cs
src/PortToDocs/tests/TestData/Exception_ExistingCref/xml_expected/MyAssembly/MyType.xml
src/PortToDocs/tests/TestData/Exceptions/xml_expected/MyAssembly/MyType.xml

cc @gewarren @tannergooding since all the Intrinsics items were not getting ported correctly.

Convert paragraphs divided by newlines into para items.

---

src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs.Strings.Tests.cs

The compiled xml files are sometimes generating this weird element instead of the correct one. This fixes it.

Replace "code data-dev-comment-type" and "xref data-throw-if-not-resolved" elements with the correct one

---

src/PortToDocs/src/app/PortToDocs.csproj
src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs.Strings.Tests.cs

Just found that I grouped langword, paramref and typeparamref into the same conversion. Only langword should use `see`, the other two have their own tag names.
Found bug in https://github.com/dotnet/dotnet-api-docs/pull/10212

Fix bug in code data-dev-comment conversions.

---

src/PortToDocs/src/app/PortToDocs.csproj
src/PortToDocs/src/libraries/XmlHelper.cs
src/PortToDocs/tests/PortToDocs.Strings.Tests.cs

Improve the logic that wraps paragraphs with `<para></para>`:
- Join paragraphs separated by newlines.
- Split paragraphs that end in "." or ":".
- Treat "-or-" and "- or -" as their own paragraphs.
- Make sure single paragraphs are not wrapped.
- Make sure empty newlines are ignored.
I'd appreciate a review from the folks who noticed the noisy `<para>` when porting, @eiriktsarpalis @Jozkee @gewarren @lonitra

Fix more <para> cases
